apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-blog
  labels:
    app: go-blog
  namespace: go-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-blog
  template:
    metadata:
      labels:
        app: go-blog
    spec:
      containers:
      - name: go-blog
        image: ghcr.io/guidonguido/go-blog:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
            