apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: asciinema-server
  namespace: go-blog
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`asciinema.guidongui.com`)
    kind: Rule
    priority: 10
    services:
    - name: asciinema-server
      port: 80
  tls:
    # secretName is the name of the secret containing the certificate
    secretName: asciinema-server-certificate-secret