apiVersion: v1
kind: Service
metadata:
  name: asciinema-server
  namespace: go-blog
spec:
  selector:
    app: asciinema-server
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 4000
    - protocol: TCP
      name: admin
      port: 4002
      targetPort: 4002
